POST http://localhost:8000/v1/auth/register
Content-Type: application/json

{
    "email": "peter@mail.com",
    "password": "peter123" 
}

###

POST http://localhost:8000/v1/auth/login
Content-Type: application/json

{
    "email": "peter@mail.com",
    "password": "peter123" 
}

###

POST http://localhost:8000/v1/content/tasks
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjUyOTA3OTUwfQ.63iDHNpHveG70Q8bAq_YCbKHQKRR1i78w5OfGrlCtiQ
Content-Type: application/json

{
    "user_id": 5,
    "description": "Go sports"
}

###

GET http://localhost:8000/v1/content/tasks
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjUyOTA3OTUwfQ.63iDHNpHveG70Q8bAq_YCbKHQKRR1i78w5OfGrlCtiQ

###
GET http://localhost:8000/v1/auth/login
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjUyODYwNDk0fQ.zaiKR26tP-sTSx042Z-Nnk2SXXZWUfne1uFziFWnPH0